name: Build FFmpeg for Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NDK_VERSION: "26.2.11394342"

jobs:
  build:
    strategy:
      matrix:
        arch: [arm64, armv7, armv7neon, x86, x86_64]
        include:
          - arch: arm64
            cross_prefix: aarch64-linux-android-
            arch_flag: aarch64
            cpu: armv8-a
            cc: aarch64-linux-android21-clang
            cxx: aarch64-linux-android21-clang++
            openssl_arch: android-arm64
          - arch: armv7
            cross_prefix: arm-linux-androideabi-
            arch_flag: arm
            cpu: armv7-a
            cc: armv7a-linux-androideabi21-clang
            cxx: armv7a-linux-androideabi21-clang++
            openssl_arch: android-arm
          - arch: armv7neon
            cross_prefix: arm-linux-androideabi-
            arch_flag: arm
            cpu: armv7-a
            cc: armv7a-linux-androideabi21-clang
            cxx: armv7a-linux-androideabi21-clang++
            openssl_arch: android-arm
          - arch: x86
            cross_prefix: i686-linux-android-
            arch_flag: x86
            cpu: i686
            cc: i686-linux-android21-clang
            cxx: i686-linux-android21-clang++
            openssl_arch: android-x86
          - arch: x86_64
            cross_prefix: x86_64-linux-android-
            arch_flag: x86_64
            cpu: x86-64
            cc: x86_64-linux-android21-clang
            cxx: x86_64-linux-android21-clang++
            openssl_arch: android-x86_64
      fail-fast: false
    
    runs-on: ubuntu-latest
    
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_NDK_ROOT: ${{ github.workspace }}/android-ndk

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Download and Setup NDK
      run: |
        mkdir -p ${{ github.workspace }}/android-ndk
        wget -q https://dl.google.com/android/repository/android-ndk-r26b-linux.zip
        unzip -q android-ndk-r26b-linux.zip
        mv android-ndk-r26b/* ${{ github.workspace }}/android-ndk/
        rm -rf android-ndk-r26b android-ndk-r26b-linux.zip
        echo "ANDROID_NDK_ROOT=${{ github.workspace }}/android-ndk" >> $GITHUB_ENV

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          pkg-config \
          ninja-build \
          libssl-dev \
          yasm \
          nasm \
          autoconf \
          automake \
          libtool \
          cmake

    - name: Download and Extract FFmpeg
      run: |
        git clone https://github.com/FFmpeg/FFmpeg.git ffmpeg
        cd ffmpeg
        git checkout release/6.0

    - name: Build OpenSSL
      run: |
        git clone https://github.com/openssl/openssl.git
        cd openssl
        git checkout OpenSSL_1_1_1w
        
        export ANDROID_NDK=$ANDROID_NDK_ROOT
        export PATH=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        export TOOLCHAIN=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64
        
        # Set target Android API level
        export ANDROID_API=21
        
        # Set compiler and tools based on architecture
        if [ "${{ matrix.arch }}" = "arm64" ]; then
          export CC=aarch64-linux-android$ANDROID_API-clang
        elif [ "${{ matrix.arch }}" = "armv7" ] || [ "${{ matrix.arch }}" = "armv7neon" ]; then
          export CC=armv7a-linux-androideabi$ANDROID_API-clang
        elif [ "${{ matrix.arch }}" = "x86" ]; then
          export CC=i686-linux-android$ANDROID_API-clang
        elif [ "${{ matrix.arch }}" = "x86_64" ]; then
          export CC=x86_64-linux-android$ANDROID_API-clang
        fi
        
        # Configure and build OpenSSL
        ./Configure ${{ matrix.openssl_arch }} \
          -D__ANDROID_API__=$ANDROID_API \
          no-shared \
          --prefix=${{ github.workspace }}/prebuilt/android-${{ matrix.arch }}/openssl \
          --openssldir=${{ github.workspace }}/prebuilt/android-${{ matrix.arch }}/openssl
        
        make clean
        make -j$(nproc)
        make install_sw

    - name: Build FFmpeg
      working-directory: ffmpeg
      run: |
        export PATH=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        export TOOLCHAIN=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64
        
        EXTRA_FLAGS=""
        if [ "${{ matrix.arch }}" = "armv7" ] || [ "${{ matrix.arch }}" = "armv7neon" ]; then
          EXTRA_FLAGS="--extra-cflags=-mfpu=neon --extra-cflags=-mfloat-abi=softfp"
        fi
        
        PKG_CONFIG_PATH=${{ github.workspace }}/prebuilt/android-${{ matrix.arch }}/openssl/lib/pkgconfig
        
        ./configure \
          --cross-prefix=${{ matrix.cross_prefix }} \
          --sysroot=$TOOLCHAIN/sysroot \
          --prefix=${{ github.workspace }}/prebuilt/android-${{ matrix.arch }}/ffmpeg \
          --enable-version3 \
          --arch=${{ matrix.arch_flag }} \
          --cpu=${{ matrix.cpu }} \
          --target-os=android \
          --enable-neon \
          --enable-asm \
          --enable-inline-asm \
          --enable-gpl \
          --enable-openssl \
          --enable-protocol=http \
          --enable-protocol=https \
          --extra-cflags="-I${{ github.workspace }}/prebuilt/android-${{ matrix.arch }}/openssl/include" \
          --extra-ldflags="-L${{ github.workspace }}/prebuilt/android-${{ matrix.arch }}/openssl/lib" \
          --ar=llvm-ar \
          --cc=${{ matrix.cc }} \
          --cxx=${{ matrix.cxx }} \
          --ranlib=llvm-ranlib \
          --strip=llvm-strip \
          --nm=llvm-nm \
          --disable-autodetect \
          --enable-cross-compile \
          --enable-pic \
          --enable-jni \
          --enable-optimizations \
          --enable-swscale \
          --disable-static \
          --enable-shared \
          --enable-pthreads \
          --disable-v4l2-m2m \
          --disable-outdev=fbdev \
          --disable-indev=fbdev \
          --enable-small \
          --disable-xmm-clobber-test \
          --disable-debug \
          --enable-lto \
          --disable-neon-clobber-test \
          --disable-programs \
          --enable-nonfree \
          --disable-postproc \
          $EXTRA_FLAGS

        make clean
        make -j$(nproc)
        make install

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ffmpeg-android-${{ matrix.arch }}
        path: ${{ github.workspace }}/prebuilt/android-${{ matrix.arch }}/ffmpeg/
