name: Build FFmpegKit for Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NDK_VERSION: "26.2.11394342"

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_NDK_ROOT: ${{ github.workspace }}/android-sdk/ndk/26.2.11394342

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install NDK
      run: |
        sdkmanager --install "ndk;${{ env.NDK_VERSION }}"

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          pkg-config \
          ninja-build \
          yasm \
          nasm \
          autoconf \
          automake \
          libtool \
          cmake

    - name: Build FFmpeg
      run: |
        chmod +x android.sh
        ./android.sh \
          --enable-version3 \
          --enable-neon \
          --enable-asm \
          --enable-inline-asm \
          --enable-cross-compile \
          --enable-pic \
          --enable-jni \
          --enable-optimizations \
          --enable-swscale \
          --disable-static \
          --enable-shared \
          --enable-pthreads \
          --enable-v4l2-m2m \
          --disable-outdev=fbdev \
          --disable-indev=fbdev \
          --enable-small \
          --disable-xmm-clobber-test \
          --disable-debug \
          --enable-lto \
          --disable-neon-clobber-test \
          --disable-programs \
          --disable-postproc

    - name: Upload arm64-v8a artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ffmpeg-android-arm64-v8a
        path: prebuilt/android-arm64-v8a/ffmpeg/
        if-no-files-found: warn

    - name: Upload armeabi-v7a artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ffmpeg-android-armeabi-v7a
        path: prebuilt/android-armeabi-v7a/ffmpeg/
        if-no-files-found: warn

    - name: Upload x86 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ffmpeg-android-x86
        path: prebuilt/android-x86/ffmpeg/
        if-no-files-found: warn

    - name: Upload x86_64 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ffmpeg-android-x86_64
        path: prebuilt/android-x86_64/ffmpeg/
        if-no-files-found: warn
