name: Build FFmpeg for Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NDK_VERSION: "26.2.11394342"

jobs:
  build:
    strategy:
      matrix:
        arch: [arm64, armv7, armv7neon, x86, x86_64]
        include:
          - arch: arm64
            cross_prefix: aarch64-linux-android-
            arch_flag: aarch64
            cpu: armv8-a
            cc: aarch64-linux-android21-clang
            cxx: aarch64-linux-android21-clang++
          - arch: armv7
            cross_prefix: armv7a-linux-androideabi-
            arch_flag: arm
            cpu: armv7-a
            cc: armv7a-linux-android21-clang
            cxx: armv7a-linux-android21-clang++
          - arch: armv7neon
            cross_prefix: armv7a-linux-androideabi-
            arch_flag: arm
            cpu: armv7-a
            cc: armv7a-linux-android21-clang
            cxx: armv7a-linux-android21-clang++
          - arch: x86
            cross_prefix: i686-linux-android-
            arch_flag: x86
            cpu: i686
            cc: i686-linux-android21-clang
            cxx: i686-linux-android21-clang++
          - arch: x86_64
            cross_prefix: x86_64-linux-android-
            arch_flag: x86_64
            cpu: x86-64
            cc: x86_64-linux-android21-clang
            cxx: x86_64-linux-android21-clang++
      fail-fast: false
    
    runs-on: ubuntu-latest
    
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_NDK_ROOT: ${{ github.workspace }}/android-sdk/ndk/26.2.11394342

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install NDK
      run: |
        sdkmanager --install "ndk;${{ env.NDK_VERSION }}"

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          pkg-config \
          ninja-build \
          libssl-dev \
          yasm \
          nasm \
          autoconf \
          automake \
          libtool \
          cmake

    - name: Download and Extract FFmpeg
      run: |
        git clone https://github.com/FFmpeg/FFmpeg.git ffmpeg
        cd ffmpeg
        git checkout release/6.0

    - name: Build FFmpeg
      working-directory: ffmpeg
      run: |
        export PATH=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        
        ./configure \
          --cross-prefix=${{ matrix.cross_prefix }} \
          --sysroot=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
          --prefix=${{ github.workspace }}/prebuilt/android-${{ matrix.arch }}/ffmpeg \
          --enable-version3 \
          --arch=${{ matrix.arch_flag }} \
          --cpu=${{ matrix.cpu }} \
          --target-os=android \
          --enable-neon \
          --enable-asm \
          --enable-inline-asm \
          --enable-gpl \
          --enable-openssl \
          --ar=llvm-ar \
          --cc=${{ matrix.cc }} \
          --cxx=${{ matrix.cxx }} \
          --ranlib=llvm-ranlib \
          --strip=llvm-strip \
          --nm=llvm-nm \
          --disable-autodetect \
          --enable-cross-compile \
          --enable-pic \
          --enable-jni \
          --enable-optimizations \
          --enable-swscale \
          --disable-static \
          --enable-shared \
          --enable-pthreads \
          --disable-v4l2-m2m \
          --disable-outdev=fbdev \
          --disable-indev=fbdev \
          --enable-small \
          --disable-xmm-clobber-test \
          --disable-debug \
          --enable-lto \
          --disable-neon-clobber-test \
          --disable-programs \
          --disable-postproc

        make -j$(nproc)
        make install

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ffmpeg-android-${{ matrix.arch }}
        path: ${{ github.workspace }}/prebuilt/android-${{ matrix.arch }}/ffmpeg/
